esphome:
  name: pms5003-1

esp8266:
  board: d1_mini

# Enable logging
logger:

ota:
  password: !secret ota_password

mqtt:
  broker: !secret mqtt_host
  username: !secret mqtt_username
  password: !secret mqtt_password
  discovery: true

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Pms5003-1 Fallback Hotspot"
    password: !secret wifi_fallback_password

captive_portal:

switch:
  - platform: gpio
    pin:
      number: D2 # Hook to the Set pin of the PMS air quality sensor
      inverted: no
    id: pms_awake

uart:
  rx_pin: D3
  tx_pin: D8
  baud_rate: 9600

sensor:
  - platform: pmsx003
    type: PMSX003
    update_interval: 60s
    pm_1_0:
      name: "Particulate Matter <1.0µm Concentration"
    pm_2_5:
      name: "Particulate Matter <2.5µm Concentration"
    pm_10_0:
      name: "Particulate Matter <10.0µm Concentration"

interval:
  - interval: 9min
    then:
      - switch.turn_on: pms_awake
      - delay: 65s
      - switch.turn_off: pms_awake
