esphome:
  name: pms5003-1

esp8266:
  board: d1_mini

# Enable logging
logger:

ota:
  password: ""

mqtt:
  broker: !secret mqtt_host
  username: !secret mqtt_username
  password: !secret mqtt_password
  discovery: true

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Pms5003-1 Fallback Hotspot"
    password: "IVOhWj92jRMk"

captive_portal:

deep_sleep:
  run_duration: 1min
  sleep_duration: 9min

uart:
  rx_pin: D4
  tx_pin: D8
  baud_rate: 9600

sensor:
  - platform: pmsx003
    type: PMSX003
    pm_1_0:
      name: "Particulate Matter <1.0µm Concentration"
    pm_2_5:
      name: "Particulate Matter <2.5µm Concentration"
    pm_10_0:
      name: "Particulate Matter <10.0µm Concentration"
    update_interval: 30000ms
